version: '3'
services:
  nginx:
    depends_on:
      - accounts
      - frontend
      - game
      - bank
      - bet
      - websocket
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - "3050:80"
  accounts:
    build:
      dockerfile: Dockerfile.dev
      context: ./be_accounts
    volumes:
      - /app/node_modules
      - ./be_accounts:/app
    ports:
      - "4003:4003"
  bet:
    build:
      dockerfile: Dockerfile.dev
      context: ./be_betmngr
    volumes:
      - /app/node_modules
      - ./be_betmngr:/app
    ports:
      - "4005:4005"
  game:
    build:
      dockerfile: Dockerfile.dev
      context: ./be_gamemngr
    volumes:
      - /app/node_modules
      - ./be_gamemngr:/app
    ports:
      - "4004:4004"
  bank:
    build:
      dockerfile: Dockerfile.dev
      context: ./be_bankmngr
    volumes:
      - /app/node_modules
      - ./be_bankmngr:/app
    ports:
      - "4006:4006"
  websocket:
    build:
      dockerfile: Dockerfile.dev
      context: ./websocket
    volumes:
      - /app/node_modules
      - ./websocket:/app
    ports:
      - "3010:3010"
  frontend:
    build:
      dockerfile: Dockerfile.dev
      context: ./frontend
    volumes:
      - /app/node_modules
      - ./frontend:/app
