version: '3'
services:
  accounts:
    image: index.docker.io/mastergtech/be_accounts_prod:1.5
    restart: unless-stopped
    env_file:
      - ../environment/production/.env.acc
    volumes:
      - /var/log/app/accounts:/var/log/app
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 750M
  bet:
    image: index.docker.io/mastergtech/be_betmngr_prod:1.5
    restart: unless-stopped
    env_file:
      - ../environment/production/.env.bet
    volumes:
      - /var/log/app/betmanager:/var/log/app 
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 750M
  game:
    image: index.docker.io/mastergtech/be_gamemngr_prod:1.5
    restart: unless-stopped
    env_file:
      - ../environment/production/.env.game
    volumes:
      - /var/log/app/gamemanager:/var/log/app
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 750M
  bank:
    image: index.docker.io/mastergtech/be_bankmngr_prod:1.5
    restart: unless-stopped
    env_file:
      - ../environment/production/.env.bank
    volumes:
      - /var/log/app/bankmanager:/var/log/app 
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 750M
  websocket:
    image: index.docker.io/mastergtech/websocket_prod:1.5
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 250M
  frontend:
    image: index.docker.io/mastergtech/frontend_prod:1.5
    restart: unless-stopped
    env_file:
      - ../environment/production/.env.frontend
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G